version: "3.7"
services:
  asap-db:
    container_name: asap-db
    image: mysql:5.7
    volumes:
      - resources/script:/docker-entrypoint-initdb.d/
    restart: always
    environment:
      MYSQL_DATABASE: asap
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
  asap-back:
    container_name: asap-back
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - asap-db
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://asap-db:3306/asap
      SPRING_DATASOURCE_USER: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver

